name: Deploy Test Reports

on:
  push:
    branches: [main, master]
  workflow_run:
    workflows: ["API Tests CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy-reports:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate reports
        run: |
          npm run test:ci

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create index.html for reports
        run: |
          mkdir -p public
          cat > public/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>API Test Reports</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .header { background: #f4f4f4; padding: 20px; border-radius: 5px; }
                  .section { margin: 20px 0; }
                  .test-item { background: #f9f9f9; padding: 15px; margin: 10px 0; border-radius: 5px; }
                  .success { border-left: 5px solid #4CAF50; }
                  .error { border-left: 5px solid #f44336; }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>🧪 API Test Reports</h1>
                  <p>Last updated: $(date)</p>
                  <p>Repository: ${{ github.repository }}</p>
                  <p>Branch: ${{ github.ref_name }}</p>
                  <p>Commit: ${{ github.sha }}</p>
              </div>
              
              <div class="section">
                  <h2>📊 Test Summary</h2>
                  <div class="test-item success">
                      <h3>✅ Products API Tests</h3>
                      <p>All API endpoints tested successfully</p>
                      <ul>
                          <li>GET /products - Get all products</li>
                          <li>GET /products/1 - Get single product</li>
                          <li>POST /products/add - Add new product</li>
                          <li>PUT /products/1 - Update product</li>
                          <li>DELETE /products/1 - Delete product</li>
                      </ul>
                  </div>
              </div>
              
              <div class="section">
                  <h2>🔗 Quick Links</h2>
                  <p><a href="https://github.com/${{ github.repository }}/actions">View GitHub Actions</a></p>
                  <p><a href="https://dummyjson.com/docs/products">API Documentation</a></p>
              </div>
          </body>
          </html>
          EOF

      - name: Copy test outputs to public
        run: |
          if [ -d "output" ]; then
            cp -r output/* public/ 2>/dev/null || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

  deploy:
    needs: deploy-reports
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
